"""
Django settings for keviseals_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# settings.py (At the very top of the file)
import os
from pathlib import Path

import os

# Check if running on Linux (PythonAnywhere Production Server)
# if os.name == 'nt':  # --- WINDOWS (LOCAL) ---
#     OSGEO4W_ROOT = Path(r"C:\Users\kevin\AppData\Local\Programs\OSGeo4W")
#     OSGEO4W_BIN = OSGEO4W_ROOT / 'bin'
#     os.environ['PATH'] = str(OSGEO4W_BIN) + os.pathsep + os.environ['PATH']
#     if hasattr(os, 'add_dll_directory') and OSGEO4W_BIN.exists():
#         os.add_dll_directory(str(OSGEO4W_BIN))

#     GDAL_LIBRARY_PATH = str(OSGEO4W_BIN / 'gdal313.dll')
#     GEOS_LIBRARY_PATH = str(OSGEO4W_BIN / 'geos_c.dll')
#     # Windows needs to find the spatialite extension module specifically:
#     SPATIALITE_LIBRARY_PATH = str(OSGEO4W_BIN / 'mod_spatialite.dll')

# else:  # --- LINUX (PYTHONANYWHERE PRODUCTION) ---
#     GDAL_LIBRARY_PATH = '/usr/local/lib/libgdal.so'
#     GEOS_LIBRARY_PATH = '/usr/lib/x86_64-linux-gnu/libgeos_c.so'
#     SPATIALITE_LIBRARY_PATH = '/usr/lib/x86_64-linux-gnu/mod_spatialite.so'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f0y^3yg5(g0@-vv+-@#6mlwvh=v%id4#_5s6eb*f*(=vhu&&_0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ '*' ]


# Application definition

INSTALLED_APPS = [
      "daphne",

    "channels",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

     # third party

    

    'rest_framework',
    'rest_framework_simplejwt',
     'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'leaflet',

    # local

    'accounts',

    'properties',

    'leases',

     "chat",

      "notifications",

]


# settings.py

# Allows external scripts like Leaflet tile servers to verify your domain name
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

LOGIN_URL = "/admin/login/"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'keviseals_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'keviseals_backend.wsgi.application'

AUTH_USER_MODEL = 'accounts.User'
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

RENT_CYCLE_MINUTES = 60

BILLING_CRON_TOKEN = "9f4b7d2c8e1a5f6g3h9k7m2p4q8r1s6"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (-1.286389, 36.817223), # Example coordinates
    'DEFAULT_ZOOM': 11,
    'TILES': [
        ('Clean Map', 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', {
            'attribution': '&copy; OpenStreetMap contributors &copy; CARTO',
            'subdomains': 'abcd'
        })
    ]
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.spatialite', # <-- Native SQLite GIS Engine
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "keviseals_db",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "postgres",
        "PORT": "5432",
    }
}
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),  # 1 week
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # optional

    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'AUTH_HEADER_TYPES': ('Bearer',),
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# DEVELOPMENT ONLY
SIMULATE_B2C_SUCCESS = True

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "kevinkaranja098@gmail.com"
EMAIL_HOST_PASSWORD = "pyrhpiifpsmoxuku"  # <-- your Gmail app password (no spaces)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/home/kevinkaranja098/keviseals_backend/static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ASGI_APPLICATION = "keviseals_backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                "redis://redis:6379/0",
            ],
        },
    },
}