# Generated by Django 5.2.6 on 2026-06-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PROPERTY_MANAGER', 'Property Manager'), ('LANDLORD', 'Landlord'), ('TENANT', 'Tenant')], default='TENANT', max_length=30),
        ),
    ]
