# Generated by Django 5.2.6 on 2026-06-19 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='landlords/profile_photos/')),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='landlords/id_front/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='landlords/id_back/')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('physical_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandlordContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='contracts/generated/')),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='contracts/signed/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='contracts/signatures/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.landlordprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='tenants/profile_photos/')),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='tenants/id_front/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='tenants/id_back/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
