# Generated by Django 5.2.6 on 2026-06-19 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationotp_landlordprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlordcontract',
            old_name='signature_image',
            new_name='digital_signature',
        ),
        migrations.RenameField(
            model_name='landlordcontract',
            old_name='generated_pdf',
            new_name='generated_contract',
        ),
        migrations.RenameField(
            model_name='landlordcontract',
            old_name='signed_at',
            new_name='reviewed_at',
        ),
        migrations.RenameField(
            model_name='landlordcontract',
            old_name='signed_document',
            new_name='signed_contract',
        ),
        migrations.AddField(
            model_name='landlordcontract',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LandlordTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(default='#00A651', max_length=20)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('heading_color', models.CharField(default='#000000', max_length=20)),
                ('font_family', models.CharField(default='Poppins', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='themes/logos/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='themes/backgrounds/')),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='accounts.landlordprofile')),
            ],
        ),
    ]
