# Generated by Django 5.2.6 on 2026-06-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_unit_bathrooms_unit_bedrooms_unit_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='moveoutrequest',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='rentcharge',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='leaserequest',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='leaserequest',
            name='unit',
        ),
        migrations.DeleteModel(
            name='LeaseWallet',
        ),
        migrations.DeleteModel(
            name='MoveOutRequest',
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
        migrations.DeleteModel(
            name='RentCharge',
        ),
        migrations.DeleteModel(
            name='LeaseRequest',
        ),
    ]
