# Generated by Django 5.1.3 on 2026-06-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0004_remove_property_latitude_remove_property_longitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
