# Generated by Django 5.2.6 on 2026-06-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_signature_image_landlordcontract_digital_signature_and_more'),
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('checkout_request_id', models.CharField(blank=True, max_length=255)),
                ('merchant_request_id', models.CharField(blank=True, max_length=255)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='leases.lease')),
                ('lease_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='leases.leaserequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.tenantprofile')),
            ],
        ),
    ]
