# Generated by Django 5.1.3 on 2026-06-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="deposit_held",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="leaserequest",
            name="deposit_required",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="leaserequest",
            name="rent_required",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
