# Generated by Django 5.1.3 on 2026-06-25 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0003_lease_deposit_held_leaserequest_deposit_required_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rentcharge",
            options={"ordering": ["billing_month"]},
        ),
        migrations.AddField(
            model_name="lease",
            name="last_billing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentcharge",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rentcharge",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("PARTIAL", "Partial"),
                    ("UNPAID", "Unpaid"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rentcharge",
            unique_together={("lease", "billing_month")},
        ),
    ]
