# Generated by Django 5.1.3 on 2026-06-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0004_alter_rentcharge_options_lease_last_billing_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rentcharge",
            unique_together=set(),
        ),
    ]
