# Generated by Django 5.1.3 on 2026-06-26 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0005_alter_rentcharge_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moveoutrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="moveoutrequest",
            name="landlord_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="moveoutrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="moveoutrequest",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="move_out_requests",
                to="leases.lease",
            ),
        ),
        migrations.AlterField(
            model_name="moveoutrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
