# Generated by Django 5.1.3 on 2026-06-26 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_signature_image_landlordcontract_digital_signature_and_more",
        ),
        ("leases", "0006_alter_moveoutrequest_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspection_date", models.DateField(auto_now_add=True)),
                ("general_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("COMPLETED", "Completed")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_inspections",
                        to="accounts.landlordprofile",
                    ),
                ),
                (
                    "move_out_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection",
                        to="leases.moveoutrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="leases.propertyinspection",
                    ),
                ),
            ],
        ),
    ]
