# Generated by Django 5.1.3 on 2026-06-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0008_leasesettlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="moveoutrequest",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
