# Generated by Django 5.1.3 on 2026-06-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0009_moveoutrequest_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasesettlement",
            name="balance_received",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leasesettlement",
            name="balance_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leasesettlement",
            name="payment_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leasesettlement",
            name="refund_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leasesettlement",
            name="refund_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leasesettlement",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FINALIZED", "Finalized"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
