# Generated by Django 5.1.3 on 2026-06-26 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0010_leasesettlement_balance_received_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leasesettlement",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("WAITING_FOR_TENANT_PAYMENT", "Waiting For Tenant Payment"),
                    ("WAITING_FOR_REFUND", "Waiting For Refund"),
                    ("FINANCIALLY_SETTLED", "Financially Settled"),
                    ("FINALIZED", "Finalized"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="SettlementTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("COLLECTION", "Collection"), ("REFUND", "Refund")],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("MPESA_STK", "M-Pesa STK"),
                            ("MPESA_B2C", "M-Pesa B2C"),
                            ("BANK", "Bank Transfer"),
                            ("CASH", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("checkout_request_id", models.CharField(blank=True, max_length=255)),
                ("merchant_request_id", models.CharField(blank=True, max_length=255)),
                ("mpesa_receipt", models.CharField(blank=True, max_length=255)),
                ("reference", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="leases.leasesettlement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
