# Generated by Django 5.1.3 on 2026-06-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0011_alter_leasesettlement_status_settlementtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlementtransaction",
            name="conversation_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="settlementtransaction",
            name="originator_conversation_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="settlementtransaction",
            name="result_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="settlementtransaction",
            name="result_desc",
            field=models.TextField(blank=True),
        ),
    ]
