# Generated by Django 5.1.3 on 2026-06-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0012_settlementtransaction_conversation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="entry_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
