# Generated by Django 5.1.3 on 2026-07-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
