# Generated by Django 5.1.3 on 2026-07-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_device_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('payment', 'Payment'), ('invoice', 'Invoice'), ('lease', 'Lease'), ('maintenance', 'Maintenance'), ('property', 'Property'), ('account', 'Account'), ('security', 'Security'), ('announcement', 'Announcement'), ('reminder', 'Reminder'), ('system', 'System')], max_length=30),
        ),
    ]
